# This file was generated by GoReleaser. DO NOT EDIT.
class Gogitmoji < Formula
  desc "gogitmoji helps you write git commit messages containing gitmoji!"
  homepage "https://github.com/jamesdobson/gogitmoji"
  version "1.0.2"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/jamesdobson/gogitmoji/releases/download/v1.0.2/gogitmoji_1.0.2_macOS_x86_64.tar.gz"
    sha256 "02e54a04aaae694f0f73c31f7062c783d3b8e62e3ff6b8335e25cd8f47fd8e0c"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/jamesdobson/gogitmoji/releases/download/v1.0.2/gogitmoji_1.0.2_Linux_x86_64.tar.gz"
      sha256 "d25c4ac5c332abf5182f67c55e6a015102dcacdd831851954e5d10b4073f1592"
    end
  end

  def install
    bin.install "gitmoji"
  end
end
