# This file was generated by GoReleaser. DO NOT EDIT.
class Gogitmoji < Formula
  desc "gogitmoji helps you write git commit messages containing gitmoji!"
  homepage "https://github.com/jamesdobson/gogitmoji"
  version "1.1.2"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/jamesdobson/gogitmoji/releases/download/v1.1.2/gogitmoji_1.1.2_macOS_x86_64.tar.gz"
    sha256 "5d9d006f56666a7986bee1feb53f049c5614d12ebd819560fc0a82ef2efc3919"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/jamesdobson/gogitmoji/releases/download/v1.1.2/gogitmoji_1.1.2_Linux_x86_64.tar.gz"
      sha256 "ba7130c4922568a22990f5f11bac610bbd7630dcbfd993db36ca5a6605388bf7"
    end
  end

  def install
    bin.install "gitmoji"
  end
end
